# Generated by Django 6.0.2 on 2026-07-14 05:46

import django.utils.timezone
from django.db import migrations, models


def deduplicate_roll_nos(apps, schema_editor):
    Enrollment = apps.get_model("enrollments", "Enrollment")
    from django.db.models import Count

    dupes = (
        Enrollment.objects.values("class_field_id", "section_id", "session_id", "roll_no")
        .filter(roll_no__gt="")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for dup in dupes:
        ids = list(
            Enrollment.objects.filter(
                class_field_id=dup["class_field_id"],
                section_id=dup["section_id"],
                session_id=dup["session_id"],
                roll_no=dup["roll_no"],
            ).values_list("id", flat=True)
        )
        keep = ids[0]
        Enrollment.objects.filter(id__in=ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(deduplicate_roll_nos, migrations.RunPython.noop, atomic=False),
    ]
