# Generated by Django 6.0.2 on 2026-07-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollments', '0002_add_roll_no_unique_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_no__gt', '')), fields=('class_field', 'section', 'session', 'roll_no'), name='unique_roll_no_per_class_section_session'),
        ),
    ]
