# Generated by Django 6.0.6 on 2026-07-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_systemsetting_student_registration_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['-created_at']},
        ),
    ]
