# Generated by Django 6.0.6 on 2026-07-14 03:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academic_sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.PositiveIntegerField(help_text='Numeric level for ordering')),
            ],
            options={
                'db_table': 'classes',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='Rendering preferences: margins, orientation, font sizes, colors')),
            ],
            options={
                'db_table': 'report_card_templates',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_scholastic', models.BooleanField(default=True, help_text='Affects percentage calculation')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'subject_categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'terms',
                'ordering': ['session', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicsession')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['session', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ExamComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', help_text='Optional short code for matching', max_length=30)),
                ('value_type', models.CharField(choices=[('numeric', 'Numeric Marks'), ('grade', 'Grade Only'), ('descriptive', 'Descriptive')], default='numeric', help_text='What kind of value this component stores', max_length=20)),
                ('full_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Required for numeric type, null for grade/descriptive', max_digits=6, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_optional', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='academics.exam')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='academics.examcomponent')),
            ],
            options={
                'db_table': 'exam_components',
                'ordering': ['exam', 'parent__id', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='academics.academicsession')),
            ],
            options={
                'db_table': 'grade_scales',
            },
        ),
        migrations.CreateModel(
            name='GradeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('display_order', models.PositiveIntegerField()),
                ('grade_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='academics.gradescale')),
            ],
            options={
                'db_table': 'grade_rules',
                'ordering': ['grade_scale', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_percentage', models.DecimalField(decimal_places=2, default=33.0, max_digits=5)),
                ('max_subjects_fail', models.PositiveIntegerField(default=0, help_text='Max subjects a student can fail and still be promoted')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules_from', to='academics.class')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='academics.academicsession')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules_to', to='academics.class')),
            ],
            options={
                'db_table': 'promotion_rules',
            },
        ),
        migrations.CreateModel(
            name='ReportCardSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('school_header', 'School Header'), ('student_details', 'Student Details'), ('scholastic_table', 'Scholastic Subjects Table'), ('co_scholastic', 'Co-Scholastic Areas'), ('discipline', 'Discipline Record'), ('attendance', 'Attendance Summary'), ('remarks', 'Remarks'), ('promotion_status', 'Promotion Status'), ('signatures', 'Signature Block'), ('grading_scale', 'Grading Scale'), ('summary_card', 'Result Summary Card')], max_length=50)),
                ('display_order', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Per-section rendering options (column widths, label overrides, visibility)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.reportcardtemplate')),
            ],
            options={
                'db_table': 'report_card_sections',
                'ordering': ['template', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardTemplateAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='academics.class')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='academics.academicsession')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.reportcardtemplate')),
            ],
            options={
                'db_table': 'report_card_template_assignments',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.class')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['class_ref', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentComponentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_marks', models.DecimalField(decimal_places=2, help_text='Override component full_marks per class-subject-session', max_digits=6)),
                ('weightage_pct', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_applicable', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(help_text='Session-scoped so historical report cards remain valid', on_delete=django.db.models.deletion.CASCADE, related_name='component_configs', to='academics.academicsession')),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='component_configs', to='academics.class')),
                ('assessment_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_configs', to='academics.examcomponent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_configs', to='academics.subject')),
            ],
            options={
                'db_table': 'assessment_component_configs',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.subjectcategory'),
        ),
        migrations.CreateModel(
            name='ReportCardSectionSubjectGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('include_scholastic', models.BooleanField(default=False, help_text='Shortcut: include all scholastic subjects')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='academics.reportcardsection')),
                ('subject_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_card_sections', to='academics.subjectcategory')),
            ],
            options={
                'db_table': 'report_card_section_subject_groups',
                'ordering': ['section', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.subjectcategory')),
            ],
            options={
                'db_table': 'subject_groups',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.subjectgroup'),
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='academics.subjectgroup')),
            ],
            options={
                'db_table': 'class_subjects',
                'ordering': ['class_ref', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
            ],
            options={
                'db_table': 'teacher_assignments',
            },
        ),
    ]
