# Generated by Django 6.0.6 on 2026-07-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='identity.teacherprofile'),
        ),
        migrations.AddField(
            model_name='term',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.term'),
        ),
        migrations.AlterUniqueTogether(
            name='examcomponent',
            unique_together={('exam', 'parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('session', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='promotionrule',
            unique_together={('session', 'from_class')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcardtemplateassignment',
            unique_together={('template', 'class_ref', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('class_ref', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcomponentconfig',
            unique_together={('class_ref', 'subject', 'session', 'assessment_component')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_ref', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'class_ref', 'section', 'subject', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('session', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('session', 'name')},
        ),
    ]
