# Generated by Django 6.0.6 on 2026-06-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='identity.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('class_ref', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_ref', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentweightage',
            unique_together={('class_ref', 'subject', 'assessment_type')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'class_ref', 'section', 'subject', 'session')},
        ),
    ]
