# Generated by Django 6.0.6 on 2026-07-11 09:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_term_assessmenttype_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_marks', models.PositiveIntegerField(default=0)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_distributions', to='academics.assessmenttype')),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='marks_distributions', to='academics.class')),
            ],
            options={
                'db_table': 'marks_distributions',
                'ordering': ['class_ref__level', 'assessment_type__display_order'],
                'unique_together': {('class_ref', 'assessment_type')},
            },
        ),
    ]
