# Generated by Django 6.0.2 on 2026-07-11 12:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_marksdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_scholastic', models.BooleanField(default=True, help_text='Affects percentage calculation')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'subject_categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='default_full_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_type',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicsession')),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['session', 'display_order'],
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExamComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', help_text='Optional short code for matching', max_length=30)),
                ('full_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_grade_only', models.BooleanField(default=False, help_text='No marks entered — only a grade (e.g., co-scholastic)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='academics.exam')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='academics.examcomponent')),
            ],
            options={
                'db_table': 'exam_components',
                'ordering': ['exam', 'parent__id', 'display_order'],
                'unique_together': {('exam', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradePolicySet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_policy_sets', to='academics.academicsession')),
            ],
            options={
                'db_table': 'grade_policy_sets',
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradePolicyGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_label', models.CharField(max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('display_order', models.PositiveIntegerField()),
                ('grade_policy_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.gradepolicyset')),
            ],
            options={
                'db_table': 'grade_policy_grades',
                'ordering': ['grade_policy_set', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.JSONField(help_text='JSON configuration defining report card sections, columns, and layout')),
                ('class_ref', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_card_templates', to='academics.class')),
            ],
            options={
                'db_table': 'report_card_templates',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.subjectcategory'),
        ),
        migrations.CreateModel(
            name='ExamComponentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_marks', models.DecimalField(decimal_places=2, help_text='Override ExamComponent.full_marks per class-subject', max_digits=6)),
                ('weightage_pct', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_component_mappings', to='academics.class')),
                ('exam_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subject_mappings', to='academics.examcomponent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_component_mappings', to='academics.subject')),
            ],
            options={
                'db_table': 'exam_component_mappings',
                'ordering': ['class_ref__level', 'subject__code', 'display_order'],
                'unique_together': {('class_ref', 'subject', 'exam_component')},
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_percentage', models.DecimalField(decimal_places=2, default=33.0, max_digits=5)),
                ('max_subjects_fail', models.PositiveIntegerField(default=0, help_text='Max subjects a student can fail and still be promoted')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules_from', to='academics.class')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='academics.academicsession')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules_to', to='academics.class')),
            ],
            options={
                'db_table': 'promotion_rules',
                'unique_together': {('session', 'from_class')},
            },
        ),
    ]
