# Generated by Django 6.0.2 on 2026-07-11 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subjectcategory_remove_subject_default_full_marks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marksdistribution',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='examcomponentmapping',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='full_marks',
        ),
        migrations.RemoveField(
            model_name='examcomponent',
            name='is_grade_only',
        ),
        migrations.RemoveField(
            model_name='reportcardtemplate',
            name='class_ref',
        ),
        migrations.RemoveField(
            model_name='reportcardtemplate',
            name='config',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject_group',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('language', 'Language'), ('vocational', 'Vocational'), ('co_scholastic', 'Co-Scholastic')], default='core', max_length=30),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.term'),
        ),
        migrations.AddField(
            model_name='examcomponent',
            name='value_type',
            field=models.CharField(choices=[('numeric', 'Numeric Marks'), ('grade', 'Grade Only'), ('descriptive', 'Descriptive')], default='numeric', help_text='What kind of value this component stores', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcardtemplate',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, help_text='Rendering preferences: margins, orientation, font sizes, colors'),
        ),
        migrations.AlterField(
            model_name='assessmentweightage',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightages+', to='academics.assessmenttype'),
        ),
        migrations.AlterField(
            model_name='assessmentweightage',
            name='class_ref',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_weightages+', to='academics.class'),
        ),
        migrations.AlterField(
            model_name='assessmentweightage',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_weightages+', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='examcomponent',
            name='full_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for numeric type, null for grade/descriptive', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='examcomponentmapping',
            name='class_ref',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_component_mappings+', to='academics.class'),
        ),
        migrations.AlterField(
            model_name='examcomponentmapping',
            name='exam_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subject_mappings+', to='academics.examcomponent'),
        ),
        migrations.AlterField(
            model_name='examcomponentmapping',
            name='full_marks',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='examcomponentmapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_component_mappings+', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='marksdistribution',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_distributions+', to='academics.assessmenttype'),
        ),
        migrations.AlterField(
            model_name='marksdistribution',
            name='class_ref',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='marks_distributions+', to='academics.class'),
        ),
        migrations.CreateModel(
            name='ReportCardSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('school_header', 'School Header'), ('student_details', 'Student Details'), ('scholastic_table', 'Scholastic Subjects Table'), ('co_scholastic', 'Co-Scholastic Areas'), ('discipline', 'Discipline Record'), ('attendance', 'Attendance Summary'), ('remarks', 'Remarks'), ('promotion_status', 'Promotion Status'), ('signatures', 'Signature Block'), ('grading_scale', 'Grading Scale'), ('summary_card', 'Result Summary Card')], max_length=50)),
                ('display_order', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Per-section rendering options (column widths, label overrides, visibility)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.reportcardtemplate')),
            ],
            options={
                'db_table': 'report_card_sections',
                'ordering': ['template', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardSectionSubjectGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('include_scholastic', models.BooleanField(default=False, help_text='Shortcut: include all scholastic subjects')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='academics.reportcardsection')),
                ('subject_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_card_sections', to='academics.subjectcategory')),
            ],
            options={
                'db_table': 'report_card_section_subject_groups',
                'ordering': ['section', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardTemplateAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='academics.class')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='academics.academicsession')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.reportcardtemplate')),
            ],
            options={
                'db_table': 'report_card_template_assignments',
                'unique_together': {('template', 'class_ref', 'session')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAssessmentScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_marks', models.DecimalField(decimal_places=2, help_text='Override ExamComponent.full_marks per class-subject-session', max_digits=6)),
                ('weightage_pct', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schemes', to='academics.class')),
                ('exam_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schemes', to='academics.examcomponent')),
                ('session', models.ForeignKey(help_text='Session-scoped so historical report cards remain valid', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schemes', to='academics.academicsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schemes', to='academics.subject')),
            ],
            options={
                'db_table': 'subject_assessment_schemes',
                'ordering': ['class_ref__level', 'subject__code', 'display_order'],
                'unique_together': {('class_ref', 'subject', 'session', 'exam_component')},
            },
        ),
    ]
