# Generated by Django 6.0.6 on 2026-07-14 03:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'term_attendances',
                'ordering': ['enrollment', 'term'],
            },
        ),
    ]
