# Generated by Django 6.0.6 on 2026-07-11 08:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_term_assessmenttype_term'),
        ('enrollments', '0003_alter_systemsetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_attendances', to='enrollments.enrollment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_attendances', to='academics.term')),
            ],
            options={
                'db_table': 'term_attendances',
                'ordering': ['enrollment', 'term'],
                'unique_together': {('enrollment', 'term')},
            },
        ),
    ]
