# Generated by Django 6.0.6 on 2026-07-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termattendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_attendances', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='termattendance',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_attendances', to='academics.term'),
        ),
        migrations.AlterUniqueTogether(
            name='termattendance',
            unique_together={('enrollment', 'term')},
        ),
    ]
